version: '3.1'

services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: shaogat81@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678

  db:
    image: postgres
    container_name: pgdb_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password

volumes:
  postgresql_data : {}